### ISSUE TITLE
task_mock crashes

### ISSUE THREAD

**Issue by devkral** [ulamlabs/celery-mock#1]
It seems like after an API change the mocking crashes. Here is the relevant part of the traceback, I inline it:

  File ".../mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File ".../mock/mock.py", line 1128, in _mock_call
    ret_val = effect(*args, **kwargs)
TypeError: _apply_async() missing 2 required positional arguments: 'a' and 'kw'

Software:
python 3.7, celery 4.3

**Comment by maiiku** [comment]
Hello,

It should be fixed in the new version (1.1.6), sorry for the long wait.
